# Generated by Django 6.0.7 on 2026-07-10 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('property', 'Property'), ('equipment', 'Equipment'), ('service', 'Service')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(help_text='e.g., Chinhoyi CBD, Mzari', max_length=100)),
                ('image', models.ImageField(upload_to='listings/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
