# Generated by Django 6.0.7 on 2026-07-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('property', 'Property'), ('equipment', 'Equipment'), ('service', 'Service'), ('other', 'Other')], max_length=20),
        ),
    ]
