# Generated by Django 6.0.7 on 2026-07-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
