# Generated by Django 6.0.7 on 2026-07-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_options_remove_listing_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_message',
            field=models.TextField(default=1, help_text='Details for your request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
