# Generated by Django 6.0.7 on 2026-07-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
