# Generated by Django 6.0.7 on 2026-07-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_review_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='product_name',
        ),
    ]
