# Generated by Django 6.0.7 on 2026-07-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_rename_title_listing_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fare_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
