# Generated by Django 6.0.7 on 2026-07-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_booking_fare_paid_booking_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
