# Generated by Django 6.0.7 on 2026-07-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language_preference',
            field=models.CharField(default='en', help_text='Preferred language for communication', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme_preference',
            field=models.CharField(default='light', help_text='Preferred UI theme', max_length=10),
        ),
    ]
