# Generated by Django 6.0.7 on 2026-07-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_language_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('sn', 'Shona'), ('nd', 'Ndebele')], default='en', help_text='Preferred language', max_length=2),
        ),
    ]
