# Generated by Django 6.0.7 on 2026-07-10 22:57

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_provider_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='verifications/', validators=[accounts.validators.validate_id_document]),
        ),
    ]
