# Generated by Django 6.0.7 on 2026-07-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
