# Generated by Django 6.0.7 on 2026-07-11 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_payment_date_listing_payment_reference'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='listings.listing'),
            preserve_default=False,
        ),
    ]
