# Generated by Django 6.0.7 on 2026-07-11 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_payment_date_listing_payment_reference'),
        ('messaging', '0002_chatroom_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='listings.listing'),
        ),
    ]
